<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Store;
use Illuminate\Database\Seeder;

class StoresSeeder extends Seeder
{
    /**
     * Seed 100 real stores with logos and coupons.
     */
    public function run(): void
    {
        $stores = [
            // ══════════════════════════════════════════════════════════════════
            // APPAREL & CLOTHING (20 stores)
            // ══════════════════════════════════════════════════════════════════
            [
                'name' => 'ASOS',
                'slug' => 'asos',
                'logo' => 'https://logo.clearbit.com/asos.com',
                'website_url' => 'https://www.asos.com',
                'description' => 'Online fashion store for men and women. Shop the latest trends in clothing, shoes, and accessories.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'rakuten',
                'categories' => ['apparel-clothing'],
                'coupons' => [
                    ['title' => '20% Off Everything', 'code' => 'ASOS20', 'type' => 'code', 'discount_value' => '20%', 'is_verified' => true],
                    ['title' => 'Free Delivery on Orders Over £30', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free Ship', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'H&M',
                'slug' => 'h-and-m',
                'logo' => 'https://logo.clearbit.com/hm.com',
                'website_url' => 'https://www.hm.com',
                'description' => 'Fashion and quality at the best price. Shop clothing for the whole family.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'cj',
                'categories' => ['apparel-clothing'],
                'coupons' => [
                    ['title' => '15% Off Your First Order', 'code' => 'HMNEW15', 'type' => 'code', 'discount_value' => '15%', 'is_verified' => true],
                    ['title' => 'Up to 70% Off Sale Items', 'code' => null, 'type' => 'sale', 'discount_value' => '70%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Zara',
                'slug' => 'zara',
                'logo' => 'https://logo.clearbit.com/zara.com',
                'website_url' => 'https://www.zara.com',
                'description' => 'Latest fashion trends in clothing and accessories for women, men, and kids.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'direct',
                'categories' => ['apparel-clothing'],
                'coupons' => [
                    ['title' => 'Seasonal Sale - Up to 50% Off', 'code' => null, 'type' => 'sale', 'discount_value' => '50%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Uniqlo',
                'slug' => 'uniqlo',
                'logo' => 'https://logo.clearbit.com/uniqlo.com',
                'website_url' => 'https://www.uniqlo.com',
                'description' => 'High quality casual wear at affordable prices. Simple, functional clothing.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'rakuten',
                'categories' => ['apparel-clothing'],
                'coupons' => [
                    ['title' => '$10 Off Orders Over $75', 'code' => 'UNIQLO10', 'type' => 'code', 'discount_value' => '$10', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'GAP',
                'slug' => 'gap',
                'logo' => 'https://logo.clearbit.com/gap.com',
                'website_url' => 'https://www.gap.com',
                'description' => 'Modern American essentials for the whole family. Classic styles made new.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'cj',
                'categories' => ['apparel-clothing'],
                'coupons' => [
                    ['title' => '40% Off Full Price Items', 'code' => 'GAP40', 'type' => 'code', 'discount_value' => '40%', 'is_verified' => true],
                    ['title' => 'Extra 10% Off with Email Signup', 'code' => null, 'type' => 'deal', 'discount_value' => '10%', 'is_verified' => true],
                ],
            ],
            [
                'name' => "Levi's",
                'slug' => 'levis',
                'logo' => 'https://logo.clearbit.com/levi.com',
                'website_url' => 'https://www.levi.com',
                'description' => 'Iconic American denim brand. Jeans, jackets, and more since 1853.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'rakuten',
                'categories' => ['apparel-clothing'],
                'coupons' => [
                    ['title' => '30% Off Sitewide', 'code' => 'LEVIS30', 'type' => 'code', 'discount_value' => '30%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Shein',
                'slug' => 'shein',
                'logo' => 'https://logo.clearbit.com/shein.com',
                'website_url' => 'https://www.shein.com',
                'description' => 'Affordable trendy fashion for women. Thousands of new styles every day.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'admitad',
                'categories' => ['apparel-clothing'],
                'coupons' => [
                    ['title' => '15% Off First Order', 'code' => 'SHEIN15', 'type' => 'code', 'discount_value' => '15%', 'is_verified' => true],
                    ['title' => 'Free Shipping Over $49', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free Ship', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'PrettyLittleThing',
                'slug' => 'prettylittlething',
                'logo' => 'https://logo.clearbit.com/prettylittlething.com',
                'website_url' => 'https://www.prettylittlething.com',
                'description' => "Women's fashion destination. Bold and trendy styles at unbeatable prices.",
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['apparel-clothing'],
                'coupons' => [
                    ['title' => '50% Off Everything', 'code' => 'PLT50', 'type' => 'code', 'discount_value' => '50%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Boohoo',
                'slug' => 'boohoo',
                'logo' => 'https://logo.clearbit.com/boohoo.com',
                'website_url' => 'https://www.boohoo.com',
                'description' => 'Fast fashion for women. Stay ahead of trends with new arrivals daily.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'awin',
                'categories' => ['apparel-clothing'],
                'coupons' => [
                    ['title' => '40% Off All Orders', 'code' => 'BOO40', 'type' => 'code', 'discount_value' => '40%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'NEXT',
                'slug' => 'next',
                'logo' => 'https://logo.clearbit.com/next.co.uk',
                'website_url' => 'https://www.next.co.uk',
                'description' => 'British fashion retailer. Quality clothing, footwear, and homeware.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['apparel-clothing', 'home-garden'],
                'coupons' => [
                    ['title' => 'Up to 50% Off Sale', 'code' => null, 'type' => 'sale', 'discount_value' => '50%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Marks & Spencer',
                'slug' => 'marks-and-spencer',
                'logo' => 'https://logo.clearbit.com/marksandspencer.com',
                'website_url' => 'https://www.marksandspencer.com',
                'description' => 'Quality British clothing, food, and homeware since 1884.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['apparel-clothing', 'food-drinks'],
                'coupons' => [
                    ['title' => '20% Off Selected Lines', 'code' => 'MS20', 'type' => 'code', 'discount_value' => '20%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Mango',
                'slug' => 'mango',
                'logo' => 'https://logo.clearbit.com/mango.com',
                'website_url' => 'https://shop.mango.com',
                'description' => 'Mediterranean-inspired fashion for women, men, and kids.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'awin',
                'categories' => ['apparel-clothing'],
                'coupons' => [
                    ['title' => '25% Off New Collection', 'code' => 'MANGO25', 'type' => 'code', 'discount_value' => '25%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Forever 21',
                'slug' => 'forever21',
                'logo' => 'https://logo.clearbit.com/forever21.com',
                'website_url' => 'https://www.forever21.com',
                'description' => 'Trendy fashion for young adults at affordable prices.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'rakuten',
                'categories' => ['apparel-clothing'],
                'coupons' => [
                    ['title' => 'Buy 2 Get 1 Free', 'code' => null, 'type' => 'deal', 'discount_value' => 'B2G1', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Nordstrom',
                'slug' => 'nordstrom',
                'logo' => 'https://logo.clearbit.com/nordstrom.com',
                'website_url' => 'https://www.nordstrom.com',
                'description' => 'Premium fashion retailer with designer brands and exceptional service.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'rakuten',
                'categories' => ['apparel-clothing'],
                'coupons' => [
                    ['title' => 'Free Shipping & Returns', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free Ship', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Urban Outfitters',
                'slug' => 'urban-outfitters',
                'logo' => 'https://logo.clearbit.com/urbanoutfitters.com',
                'website_url' => 'https://www.urbanoutfitters.com',
                'description' => 'Lifestyle retailer for fashion, home decor, and vintage-inspired goods.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'rakuten',
                'categories' => ['apparel-clothing', 'home-garden'],
                'coupons' => [
                    ['title' => '15% Off Student Discount', 'code' => null, 'type' => 'deal', 'discount_value' => '15%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'River Island',
                'slug' => 'river-island',
                'logo' => 'https://logo.clearbit.com/riverisland.com',
                'website_url' => 'https://www.riverisland.com',
                'description' => 'British high street fashion for women, men, and kids.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'awin',
                'categories' => ['apparel-clothing'],
                'coupons' => [
                    ['title' => '20% Off Full Price', 'code' => 'RI20', 'type' => 'code', 'discount_value' => '20%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Topshop',
                'slug' => 'topshop',
                'logo' => 'https://logo.clearbit.com/topshop.com',
                'website_url' => 'https://www.asos.com/topshop',
                'description' => 'Iconic British fashion brand now available at ASOS.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'rakuten',
                'categories' => ['apparel-clothing'],
                'coupons' => [
                    ['title' => 'Up to 60% Off Sale', 'code' => null, 'type' => 'sale', 'discount_value' => '60%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Missguided',
                'slug' => 'missguided',
                'logo' => 'https://logo.clearbit.com/missguided.com',
                'website_url' => 'https://www.missguided.com',
                'description' => 'Empowering women through bold and fearless fashion.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'awin',
                'categories' => ['apparel-clothing'],
                'coupons' => [
                    ['title' => '30% Off Everything', 'code' => 'MG30', 'type' => 'code', 'discount_value' => '30%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Ted Baker',
                'slug' => 'ted-baker',
                'logo' => 'https://logo.clearbit.com/tedbaker.com',
                'website_url' => 'https://www.tedbaker.com',
                'description' => 'British luxury lifestyle brand known for distinctive design.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['apparel-clothing'],
                'coupons' => [
                    ['title' => '15% Off First Order', 'code' => 'TED15', 'type' => 'code', 'discount_value' => '15%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Superdry',
                'slug' => 'superdry',
                'logo' => 'https://logo.clearbit.com/superdry.com',
                'website_url' => 'https://www.superdry.com',
                'description' => 'Japanese-inspired British streetwear and premium clothing.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'awin',
                'categories' => ['apparel-clothing'],
                'coupons' => [
                    ['title' => '25% Off Full Price', 'code' => 'SD25', 'type' => 'code', 'discount_value' => '25%', 'is_verified' => true],
                ],
            ],

            // ══════════════════════════════════════════════════════════════════
            // ELECTRONICS (15 stores)
            // ══════════════════════════════════════════════════════════════════
            [
                'name' => 'Apple',
                'slug' => 'apple',
                'logo' => 'https://logo.clearbit.com/apple.com',
                'website_url' => 'https://www.apple.com',
                'description' => 'Official Apple Store. iPhone, iPad, Mac, Apple Watch, and more.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'direct',
                'categories' => ['electronics'],
                'coupons' => [
                    ['title' => 'Free Engraving on AirPods', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free', 'is_verified' => true],
                    ['title' => 'Education Pricing - Save Up to £280', 'code' => null, 'type' => 'deal', 'discount_value' => '£280', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Dell',
                'slug' => 'dell',
                'logo' => 'https://logo.clearbit.com/dell.com',
                'website_url' => 'https://www.dell.com',
                'description' => 'Computers, laptops, monitors, and technology solutions.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'cj',
                'categories' => ['electronics'],
                'coupons' => [
                    ['title' => '10% Off XPS Laptops', 'code' => 'DELLXPS10', 'type' => 'code', 'discount_value' => '10%', 'is_verified' => true],
                    ['title' => 'Free Shipping Sitewide', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free Ship', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'HP',
                'slug' => 'hp',
                'logo' => 'https://logo.clearbit.com/hp.com',
                'website_url' => 'https://www.hp.com',
                'description' => 'Laptops, printers, desktops, and business solutions.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'cj',
                'categories' => ['electronics'],
                'coupons' => [
                    ['title' => '15% Off Select Laptops', 'code' => 'HP15OFF', 'type' => 'code', 'discount_value' => '15%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Lenovo',
                'slug' => 'lenovo',
                'logo' => 'https://logo.clearbit.com/lenovo.com',
                'website_url' => 'https://www.lenovo.com',
                'description' => 'ThinkPad, IdeaPad laptops, desktops, and smart devices.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'rakuten',
                'categories' => ['electronics'],
                'coupons' => [
                    ['title' => 'Extra 5% Off with Code', 'code' => 'LENOVOSAVE', 'type' => 'code', 'discount_value' => '5%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Best Buy',
                'slug' => 'best-buy',
                'logo' => 'https://logo.clearbit.com/bestbuy.com',
                'website_url' => 'https://www.bestbuy.com',
                'description' => 'Electronics, appliances, computers, phones, and more.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'rakuten',
                'categories' => ['electronics'],
                'coupons' => [
                    ['title' => 'Deal of the Day - Up to 50% Off', 'code' => null, 'type' => 'deal', 'discount_value' => '50%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Newegg',
                'slug' => 'newegg',
                'logo' => 'https://logo.clearbit.com/newegg.com',
                'website_url' => 'https://www.newegg.com',
                'description' => 'Computer hardware, electronics, and gaming gear at great prices.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'cj',
                'categories' => ['electronics'],
                'coupons' => [
                    ['title' => 'Shell Shocker Deals - Up to 70% Off', 'code' => null, 'type' => 'deal', 'discount_value' => '70%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'B&H Photo',
                'slug' => 'bh-photo',
                'logo' => 'https://logo.clearbit.com/bhphotovideo.com',
                'website_url' => 'https://www.bhphotovideo.com',
                'description' => 'Professional photography, video, and audio equipment.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'cj',
                'categories' => ['electronics'],
                'coupons' => [
                    ['title' => 'Free Expedited Shipping', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free Ship', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Currys',
                'slug' => 'currys',
                'logo' => 'https://logo.clearbit.com/currys.co.uk',
                'website_url' => 'https://www.currys.co.uk',
                'description' => "UK's largest electrical retailer. Tech, appliances, and gaming.",
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['electronics'],
                'coupons' => [
                    ['title' => '£50 Off Large Appliances', 'code' => 'CURRYS50', 'type' => 'code', 'discount_value' => '£50', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Microsoft',
                'slug' => 'microsoft',
                'logo' => 'https://logo.clearbit.com/microsoft.com',
                'website_url' => 'https://www.microsoft.com',
                'description' => 'Surface devices, Xbox, Office 365, and Windows software.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'cj',
                'categories' => ['electronics'],
                'coupons' => [
                    ['title' => 'Student Discount - 10% Off', 'code' => null, 'type' => 'deal', 'discount_value' => '10%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Sony',
                'slug' => 'sony',
                'logo' => 'https://logo.clearbit.com/sony.com',
                'website_url' => 'https://www.sony.com',
                'description' => 'PlayStation, cameras, TVs, audio, and entertainment electronics.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'rakuten',
                'categories' => ['electronics'],
                'coupons' => [
                    ['title' => '10% Off Headphones', 'code' => 'SONY10', 'type' => 'code', 'discount_value' => '10%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'LG',
                'slug' => 'lg',
                'logo' => 'https://logo.clearbit.com/lg.com',
                'website_url' => 'https://www.lg.com',
                'description' => 'TVs, appliances, mobile phones, and home entertainment.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'cj',
                'categories' => ['electronics'],
                'coupons' => [
                    ['title' => 'Up to 30% Off Select TVs', 'code' => null, 'type' => 'deal', 'discount_value' => '30%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Bose',
                'slug' => 'bose',
                'logo' => 'https://logo.clearbit.com/bose.com',
                'website_url' => 'https://www.bose.com',
                'description' => 'Premium audio equipment. Headphones, speakers, and soundbars.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'rakuten',
                'categories' => ['electronics'],
                'coupons' => [
                    ['title' => 'Refurbished Products - Up to 30% Off', 'code' => null, 'type' => 'deal', 'discount_value' => '30%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'JBL',
                'slug' => 'jbl',
                'logo' => 'https://logo.clearbit.com/jbl.com',
                'website_url' => 'https://www.jbl.com',
                'description' => 'Portable speakers, headphones, and professional audio equipment.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'cj',
                'categories' => ['electronics'],
                'coupons' => [
                    ['title' => '20% Off Portable Speakers', 'code' => 'JBL20', 'type' => 'code', 'discount_value' => '20%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Dyson',
                'slug' => 'dyson',
                'logo' => 'https://logo.clearbit.com/dyson.com',
                'website_url' => 'https://www.dyson.com',
                'description' => 'Innovative vacuums, hair care, air purifiers, and lighting.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'rakuten',
                'categories' => ['electronics', 'home-garden'],
                'coupons' => [
                    ['title' => 'Free Accessories with V15 Purchase', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free Gift', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'AO.com',
                'slug' => 'ao',
                'logo' => 'https://logo.clearbit.com/ao.com',
                'website_url' => 'https://www.ao.com',
                'description' => 'UK appliances retailer. TVs, washing machines, fridges, and more.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'awin',
                'categories' => ['electronics', 'home-garden'],
                'coupons' => [
                    ['title' => 'Free Delivery on All Orders', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free Ship', 'is_verified' => true],
                ],
            ],

            // ══════════════════════════════════════════════════════════════════
            // HEALTH & BEAUTY (15 stores)
            // ══════════════════════════════════════════════════════════════════
            [
                'name' => 'Sephora',
                'slug' => 'sephora',
                'logo' => 'https://logo.clearbit.com/sephora.com',
                'website_url' => 'https://www.sephora.com',
                'description' => 'Beauty retailer with makeup, skincare, haircare, and fragrance.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'rakuten',
                'categories' => ['health-beauty'],
                'coupons' => [
                    ['title' => 'Free Sample Set with $35 Purchase', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free Gift', 'is_verified' => true],
                    ['title' => '15% Off for Beauty Insider Members', 'code' => null, 'type' => 'deal', 'discount_value' => '15%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Ulta Beauty',
                'slug' => 'ulta-beauty',
                'logo' => 'https://logo.clearbit.com/ulta.com',
                'website_url' => 'https://www.ulta.com',
                'description' => 'Beauty products, salon services, and fragrance.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'rakuten',
                'categories' => ['health-beauty'],
                'coupons' => [
                    ['title' => '$5 Off $15 Purchase', 'code' => 'ULTA5OFF', 'type' => 'code', 'discount_value' => '$5', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Bath & Body Works',
                'slug' => 'bath-body-works',
                'logo' => 'https://logo.clearbit.com/bathandbodyworks.com',
                'website_url' => 'https://www.bathandbodyworks.com',
                'description' => 'Body care, home fragrance, and beauty products.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'rakuten',
                'categories' => ['health-beauty'],
                'coupons' => [
                    ['title' => 'Buy 3 Get 3 Free', 'code' => null, 'type' => 'deal', 'discount_value' => 'B3G3', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'The Body Shop',
                'slug' => 'the-body-shop',
                'logo' => 'https://logo.clearbit.com/thebodyshop.com',
                'website_url' => 'https://www.thebodyshop.com',
                'description' => 'Ethical beauty products. Skincare, body care, and makeup.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'awin',
                'categories' => ['health-beauty'],
                'coupons' => [
                    ['title' => '40% Off Sitewide', 'code' => 'BODY40', 'type' => 'code', 'discount_value' => '40%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Lush',
                'slug' => 'lush',
                'logo' => 'https://logo.clearbit.com/lush.com',
                'website_url' => 'https://www.lush.com',
                'description' => 'Fresh handmade cosmetics. Bath bombs, soaps, and skincare.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'direct',
                'categories' => ['health-beauty'],
                'coupons' => [
                    ['title' => 'Free Shipping Over £45', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free Ship', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Boots',
                'slug' => 'boots',
                'logo' => 'https://logo.clearbit.com/boots.com',
                'website_url' => 'https://www.boots.com',
                'description' => 'UK pharmacy and beauty retailer. Health, beauty, and pharmacy.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['health-beauty'],
                'coupons' => [
                    ['title' => '£10 Worth of Points on £60 Spend', 'code' => null, 'type' => 'deal', 'discount_value' => '£10 Points', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Superdrug',
                'slug' => 'superdrug',
                'logo' => 'https://logo.clearbit.com/superdrug.com',
                'website_url' => 'https://www.superdrug.com',
                'description' => 'Health and beauty retailer with pharmacy services.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'awin',
                'categories' => ['health-beauty'],
                'coupons' => [
                    ['title' => '3 for 2 on Selected Beauty', 'code' => null, 'type' => 'deal', 'discount_value' => '3 for 2', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Glossier',
                'slug' => 'glossier',
                'logo' => 'https://logo.clearbit.com/glossier.com',
                'website_url' => 'https://www.glossier.com',
                'description' => 'Skincare and makeup for real life. Beauty essentials.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'direct',
                'categories' => ['health-beauty'],
                'coupons' => [
                    ['title' => '10% Off First Order', 'code' => 'GLOSSIER10', 'type' => 'code', 'discount_value' => '10%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Charlotte Tilbury',
                'slug' => 'charlotte-tilbury',
                'logo' => 'https://logo.clearbit.com/charlottetilbury.com',
                'website_url' => 'https://www.charlottetilbury.com',
                'description' => 'Luxury makeup and skincare by celebrity makeup artist.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['health-beauty'],
                'coupons' => [
                    ['title' => 'Free Magic Cream Sample', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free Sample', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'MAC Cosmetics',
                'slug' => 'mac-cosmetics',
                'logo' => 'https://logo.clearbit.com/maccosmetics.com',
                'website_url' => 'https://www.maccosmetics.com',
                'description' => 'Professional quality makeup for all ages, races, and genders.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'rakuten',
                'categories' => ['health-beauty'],
                'coupons' => [
                    ['title' => 'Free Shipping on All Orders', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free Ship', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Clinique',
                'slug' => 'clinique',
                'logo' => 'https://logo.clearbit.com/clinique.com',
                'website_url' => 'https://www.clinique.com',
                'description' => 'Allergy tested, 100% fragrance free skincare and makeup.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'rakuten',
                'categories' => ['health-beauty'],
                'coupons' => [
                    ['title' => 'Free 7-Piece Gift with Purchase', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free Gift', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Look Fantastic',
                'slug' => 'look-fantastic',
                'logo' => 'https://logo.clearbit.com/lookfantastic.com',
                'website_url' => 'https://www.lookfantastic.com',
                'description' => 'Online beauty retailer with premium hair, skin, and makeup.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['health-beauty'],
                'coupons' => [
                    ['title' => '20% Off First Order', 'code' => 'LFNEW20', 'type' => 'code', 'discount_value' => '20%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Cult Beauty',
                'slug' => 'cult-beauty',
                'logo' => 'https://logo.clearbit.com/cultbeauty.co.uk',
                'website_url' => 'https://www.cultbeauty.co.uk',
                'description' => 'Curated beauty retailer featuring hard-to-find brands.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'awin',
                'categories' => ['health-beauty'],
                'coupons' => [
                    ['title' => '15% Off for New Customers', 'code' => 'CULT15', 'type' => 'code', 'discount_value' => '15%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'GNC',
                'slug' => 'gnc',
                'logo' => 'https://logo.clearbit.com/gnc.com',
                'website_url' => 'https://www.gnc.com',
                'description' => 'Vitamins, supplements, protein, and wellness products.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'cj',
                'categories' => ['health-beauty'],
                'coupons' => [
                    ['title' => 'Buy 2 Get 1 Free on Vitamins', 'code' => null, 'type' => 'deal', 'discount_value' => 'B2G1', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Holland & Barrett',
                'slug' => 'holland-barrett',
                'logo' => 'https://logo.clearbit.com/hollandandbarrett.com',
                'website_url' => 'https://www.hollandandbarrett.com',
                'description' => 'Health food store with vitamins, supplements, and natural beauty.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['health-beauty'],
                'coupons' => [
                    ['title' => 'Penny Sale - Buy 1 Get 1 for 1p', 'code' => null, 'type' => 'deal', 'discount_value' => 'B1G1 1p', 'is_verified' => true],
                ],
            ],

            // ══════════════════════════════════════════════════════════════════
            // TRAVEL (15 stores)
            // ══════════════════════════════════════════════════════════════════
            [
                'name' => 'Expedia',
                'slug' => 'expedia',
                'logo' => 'https://logo.clearbit.com/expedia.com',
                'website_url' => 'https://www.expedia.com',
                'description' => 'Book flights, hotels, car rentals, and vacation packages.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'cj',
                'categories' => ['travel'],
                'coupons' => [
                    ['title' => '15% Off Hotels with App', 'code' => null, 'type' => 'deal', 'discount_value' => '15%', 'is_verified' => true],
                    ['title' => 'Bundle & Save Up to $500', 'code' => null, 'type' => 'deal', 'discount_value' => '$500', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Hotels.com',
                'slug' => 'hotels-com',
                'logo' => 'https://logo.clearbit.com/hotels.com',
                'website_url' => 'https://www.hotels.com',
                'description' => 'Book hotels worldwide. Earn free nights with rewards.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'cj',
                'categories' => ['travel'],
                'coupons' => [
                    ['title' => 'Secret Prices - Save Up to 50%', 'code' => null, 'type' => 'deal', 'discount_value' => '50%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Airbnb',
                'slug' => 'airbnb',
                'logo' => 'https://logo.clearbit.com/airbnb.com',
                'website_url' => 'https://www.airbnb.com',
                'description' => 'Unique homes, experiences, and places around the world.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'direct',
                'categories' => ['travel'],
                'coupons' => [
                    ['title' => '$50 Off First Stay', 'code' => null, 'type' => 'deal', 'discount_value' => '$50', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Skyscanner',
                'slug' => 'skyscanner',
                'logo' => 'https://logo.clearbit.com/skyscanner.net',
                'website_url' => 'https://www.skyscanner.net',
                'description' => 'Compare flights, hotels, and car rentals to find the best deals.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['travel'],
                'coupons' => [
                    ['title' => 'Best Price Guarantee', 'code' => null, 'type' => 'deal', 'discount_value' => 'Best Price', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Agoda',
                'slug' => 'agoda',
                'logo' => 'https://logo.clearbit.com/agoda.com',
                'website_url' => 'https://www.agoda.com',
                'description' => 'Hotel booking with best price guarantee. Over 2 million properties.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'cj',
                'categories' => ['travel'],
                'coupons' => [
                    ['title' => 'Up to 80% Off Flash Sales', 'code' => null, 'type' => 'deal', 'discount_value' => '80%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Trivago',
                'slug' => 'trivago',
                'logo' => 'https://logo.clearbit.com/trivago.com',
                'website_url' => 'https://www.trivago.com',
                'description' => 'Compare hotel prices from hundreds of booking sites.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'awin',
                'categories' => ['travel'],
                'coupons' => [
                    ['title' => 'Find Your Ideal Hotel', 'code' => null, 'type' => 'deal', 'discount_value' => 'Compare', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Viator',
                'slug' => 'viator',
                'logo' => 'https://logo.clearbit.com/viator.com',
                'website_url' => 'https://www.viator.com',
                'description' => 'Tours, activities, and attractions worldwide.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'cj',
                'categories' => ['travel'],
                'coupons' => [
                    ['title' => '10% Off First Booking', 'code' => 'VIATOR10', 'type' => 'code', 'discount_value' => '10%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'GetYourGuide',
                'slug' => 'getyourguide',
                'logo' => 'https://logo.clearbit.com/getyourguide.com',
                'website_url' => 'https://www.getyourguide.com',
                'description' => 'Book tours, attractions, and activities worldwide.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['travel'],
                'coupons' => [
                    ['title' => 'Free Cancellation on Most Tours', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free Cancel', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Klook',
                'slug' => 'klook',
                'logo' => 'https://logo.clearbit.com/klook.com',
                'website_url' => 'https://www.klook.com',
                'description' => 'Book travel activities, tours, and experiences.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'admitad',
                'categories' => ['travel'],
                'coupons' => [
                    ['title' => '5% Off All Activities', 'code' => 'KLOOK5', 'type' => 'code', 'discount_value' => '5%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Emirates',
                'slug' => 'emirates',
                'logo' => 'https://logo.clearbit.com/emirates.com',
                'website_url' => 'https://www.emirates.com',
                'description' => 'Award-winning airline. Book flights to 150+ destinations.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['travel'],
                'coupons' => [
                    ['title' => 'Special Fares to Dubai', 'code' => null, 'type' => 'deal', 'discount_value' => 'Special', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'British Airways',
                'slug' => 'british-airways',
                'logo' => 'https://logo.clearbit.com/britishairways.com',
                'website_url' => 'https://www.britishairways.com',
                'description' => 'Book flights, holidays, and check-in online.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['travel'],
                'coupons' => [
                    ['title' => 'Avios Points on Every Flight', 'code' => null, 'type' => 'deal', 'discount_value' => 'Points', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Qatar Airways',
                'slug' => 'qatar-airways',
                'logo' => 'https://logo.clearbit.com/qatarairways.com',
                'website_url' => 'https://www.qatarairways.com',
                'description' => "World's best airline. Book flights worldwide.",
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'admitad',
                'categories' => ['travel'],
                'coupons' => [
                    ['title' => 'Student Discount - 10% Off', 'code' => null, 'type' => 'deal', 'discount_value' => '10%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'TUI',
                'slug' => 'tui',
                'logo' => 'https://logo.clearbit.com/tui.co.uk',
                'website_url' => 'https://www.tui.co.uk',
                'description' => 'Package holidays, flights, cruises, and hotels.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['travel'],
                'coupons' => [
                    ['title' => '£100 Off Summer Holidays', 'code' => 'TUI100', 'type' => 'code', 'discount_value' => '£100', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Lastminute.com',
                'slug' => 'lastminute',
                'logo' => 'https://logo.clearbit.com/lastminute.com',
                'website_url' => 'https://www.lastminute.com',
                'description' => 'Last minute deals on flights, hotels, and holidays.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'awin',
                'categories' => ['travel'],
                'coupons' => [
                    ['title' => 'Flash Sale - Up to 40% Off', 'code' => null, 'type' => 'deal', 'discount_value' => '40%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Trainline',
                'slug' => 'trainline',
                'logo' => 'https://logo.clearbit.com/thetrainline.com',
                'website_url' => 'https://www.thetrainline.com',
                'description' => 'Book train and bus tickets across UK and Europe.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['travel'],
                'coupons' => [
                    ['title' => 'Save 1/3 with Railcard', 'code' => null, 'type' => 'deal', 'discount_value' => '33%', 'is_verified' => true],
                ],
            ],

            // ══════════════════════════════════════════════════════════════════
            // SPORTS & OUTDOORS (15 stores)
            // ══════════════════════════════════════════════════════════════════
            [
                'name' => 'Adidas',
                'slug' => 'adidas',
                'logo' => 'https://logo.clearbit.com/adidas.com',
                'website_url' => 'https://www.adidas.com',
                'description' => 'Athletic shoes, clothing, and accessories for all sports.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'rakuten',
                'categories' => ['sports-outdoors', 'apparel-clothing'],
                'coupons' => [
                    ['title' => '25% Off Full Price Items', 'code' => 'ADIDAS25', 'type' => 'code', 'discount_value' => '25%', 'is_verified' => true],
                    ['title' => 'Free Shipping for Members', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free Ship', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Puma',
                'slug' => 'puma',
                'logo' => 'https://logo.clearbit.com/puma.com',
                'website_url' => 'https://www.puma.com',
                'description' => 'Sport and lifestyle footwear, apparel, and accessories.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'cj',
                'categories' => ['sports-outdoors', 'apparel-clothing'],
                'coupons' => [
                    ['title' => '20% Off Sitewide', 'code' => 'PUMA20', 'type' => 'code', 'discount_value' => '20%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Under Armour',
                'slug' => 'under-armour',
                'logo' => 'https://logo.clearbit.com/underarmour.com',
                'website_url' => 'https://www.underarmour.com',
                'description' => 'Performance apparel, shoes, and accessories for athletes.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'rakuten',
                'categories' => ['sports-outdoors', 'apparel-clothing'],
                'coupons' => [
                    ['title' => '25% Off Outlet Items', 'code' => null, 'type' => 'deal', 'discount_value' => '25%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Reebok',
                'slug' => 'reebok',
                'logo' => 'https://logo.clearbit.com/reebok.com',
                'website_url' => 'https://www.reebok.com',
                'description' => 'Athletic footwear, apparel, and equipment.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'rakuten',
                'categories' => ['sports-outdoors', 'apparel-clothing'],
                'coupons' => [
                    ['title' => '30% Off Sale Items', 'code' => 'REEBOK30', 'type' => 'code', 'discount_value' => '30%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'New Balance',
                'slug' => 'new-balance',
                'logo' => 'https://logo.clearbit.com/newbalance.com',
                'website_url' => 'https://www.newbalance.com',
                'description' => 'Athletic footwear and apparel. Made to move.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'cj',
                'categories' => ['sports-outdoors', 'apparel-clothing'],
                'coupons' => [
                    ['title' => '10% Off First Order', 'code' => 'NB10', 'type' => 'code', 'discount_value' => '10%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Foot Locker',
                'slug' => 'foot-locker',
                'logo' => 'https://logo.clearbit.com/footlocker.com',
                'website_url' => 'https://www.footlocker.com',
                'description' => 'Athletic footwear and apparel from top brands.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'rakuten',
                'categories' => ['sports-outdoors', 'apparel-clothing'],
                'coupons' => [
                    ['title' => '$15 Off $75 Purchase', 'code' => 'FL15OFF', 'type' => 'code', 'discount_value' => '$15', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'The North Face',
                'slug' => 'the-north-face',
                'logo' => 'https://logo.clearbit.com/thenorthface.com',
                'website_url' => 'https://www.thenorthface.com',
                'description' => 'Outdoor clothing, backpacks, and equipment.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'rakuten',
                'categories' => ['sports-outdoors', 'apparel-clothing'],
                'coupons' => [
                    ['title' => 'Free Shipping on All Orders', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free Ship', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Columbia',
                'slug' => 'columbia',
                'logo' => 'https://logo.clearbit.com/columbia.com',
                'website_url' => 'https://www.columbia.com',
                'description' => 'Outdoor apparel, footwear, and gear for adventure.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'cj',
                'categories' => ['sports-outdoors', 'apparel-clothing'],
                'coupons' => [
                    ['title' => '20% Off Full Price', 'code' => 'COLUMBIA20', 'type' => 'code', 'discount_value' => '20%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Patagonia',
                'slug' => 'patagonia',
                'logo' => 'https://logo.clearbit.com/patagonia.com',
                'website_url' => 'https://www.patagonia.com',
                'description' => 'Sustainable outdoor clothing and gear. Built to last.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'direct',
                'categories' => ['sports-outdoors', 'apparel-clothing'],
                'coupons' => [
                    ['title' => 'Free Shipping Over $99', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free Ship', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Decathlon',
                'slug' => 'decathlon',
                'logo' => 'https://logo.clearbit.com/decathlon.com',
                'website_url' => 'https://www.decathlon.com',
                'description' => 'Affordable sports equipment and clothing for 80+ sports.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['sports-outdoors'],
                'coupons' => [
                    ['title' => 'Up to 50% Off Sale', 'code' => null, 'type' => 'sale', 'discount_value' => '50%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Sports Direct',
                'slug' => 'sports-direct',
                'logo' => 'https://logo.clearbit.com/sportsdirect.com',
                'website_url' => 'https://www.sportsdirect.com',
                'description' => "UK's largest sports retailer with unbeatable prices.",
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['sports-outdoors'],
                'coupons' => [
                    ['title' => 'Up to 70% Off Clearance', 'code' => null, 'type' => 'sale', 'discount_value' => '70%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'JD Sports',
                'slug' => 'jd-sports',
                'logo' => 'https://logo.clearbit.com/jdsports.co.uk',
                'website_url' => 'https://www.jdsports.co.uk',
                'description' => 'Trainers, clothing, and accessories from top brands.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['sports-outdoors', 'apparel-clothing'],
                'coupons' => [
                    ['title' => '10% Student Discount', 'code' => null, 'type' => 'deal', 'discount_value' => '10%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Gymshark',
                'slug' => 'gymshark',
                'logo' => 'https://logo.clearbit.com/gymshark.com',
                'website_url' => 'https://www.gymshark.com',
                'description' => 'Fitness apparel and accessories. Gym wear that performs.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['sports-outdoors', 'apparel-clothing'],
                'coupons' => [
                    ['title' => 'Up to 50% Off Sale', 'code' => null, 'type' => 'sale', 'discount_value' => '50%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'REI',
                'slug' => 'rei',
                'logo' => 'https://logo.clearbit.com/rei.com',
                'website_url' => 'https://www.rei.com',
                'description' => 'Outdoor gear and apparel for camping, hiking, and more.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'cj',
                'categories' => ['sports-outdoors'],
                'coupons' => [
                    ['title' => '20% Off One Full-Price Item', 'code' => 'REI20', 'type' => 'code', 'discount_value' => '20%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'ASICS',
                'slug' => 'asics',
                'logo' => 'https://logo.clearbit.com/asics.com',
                'website_url' => 'https://www.asics.com',
                'description' => 'Running shoes and athletic apparel for all athletes.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'cj',
                'categories' => ['sports-outdoors', 'apparel-clothing'],
                'coupons' => [
                    ['title' => '15% Off First Order', 'code' => 'ASICS15', 'type' => 'code', 'discount_value' => '15%', 'is_verified' => true],
                ],
            ],

            // ══════════════════════════════════════════════════════════════════
            // FOOD & DRINKS (10 stores)
            // ══════════════════════════════════════════════════════════════════
            [
                'name' => 'Uber Eats',
                'slug' => 'uber-eats',
                'logo' => 'https://logo.clearbit.com/ubereats.com',
                'website_url' => 'https://www.ubereats.com',
                'description' => 'Food delivery from local restaurants. Order now.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'cj',
                'categories' => ['food-drinks'],
                'coupons' => [
                    ['title' => '£10 Off First Order', 'code' => 'UBER10', 'type' => 'code', 'discount_value' => '£10', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Deliveroo',
                'slug' => 'deliveroo',
                'logo' => 'https://logo.clearbit.com/deliveroo.com',
                'website_url' => 'https://www.deliveroo.com',
                'description' => 'Food delivery from your favourite local restaurants.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['food-drinks'],
                'coupons' => [
                    ['title' => '25% Off First 3 Orders', 'code' => 'DELROO25', 'type' => 'code', 'discount_value' => '25%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Just Eat',
                'slug' => 'just-eat',
                'logo' => 'https://logo.clearbit.com/just-eat.co.uk',
                'website_url' => 'https://www.just-eat.co.uk',
                'description' => 'Order takeaway online from thousands of restaurants.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['food-drinks'],
                'coupons' => [
                    ['title' => '20% Off Selected Restaurants', 'code' => null, 'type' => 'deal', 'discount_value' => '20%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'HelloFresh',
                'slug' => 'hellofresh',
                'logo' => 'https://logo.clearbit.com/hellofresh.com',
                'website_url' => 'https://www.hellofresh.com',
                'description' => 'Meal kit delivery with fresh ingredients and easy recipes.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'cj',
                'categories' => ['food-drinks'],
                'coupons' => [
                    ['title' => '60% Off First Box + Free Shipping', 'code' => 'HELLO60', 'type' => 'code', 'discount_value' => '60%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Gousto',
                'slug' => 'gousto',
                'logo' => 'https://logo.clearbit.com/gousto.co.uk',
                'website_url' => 'https://www.gousto.co.uk',
                'description' => 'Recipe boxes delivered to your door. 75+ recipes weekly.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['food-drinks'],
                'coupons' => [
                    ['title' => '65% Off First Box + 30% Off Month', 'code' => 'GOUSTO65', 'type' => 'code', 'discount_value' => '65%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Dominos',
                'slug' => 'dominos',
                'logo' => 'https://logo.clearbit.com/dominos.com',
                'website_url' => 'https://www.dominos.com',
                'description' => "Pizza delivery and carryout. America's favorite pizza.",
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'cj',
                'categories' => ['food-drinks'],
                'coupons' => [
                    ['title' => '50% Off Menu Price Pizzas', 'code' => null, 'type' => 'deal', 'discount_value' => '50%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Papa Johns',
                'slug' => 'papa-johns',
                'logo' => 'https://logo.clearbit.com/papajohns.com',
                'website_url' => 'https://www.papajohns.com',
                'description' => 'Better ingredients. Better pizza. Order online.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'cj',
                'categories' => ['food-drinks'],
                'coupons' => [
                    ['title' => '25% Off Full Menu', 'code' => 'PAPA25', 'type' => 'code', 'discount_value' => '25%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Pizza Hut',
                'slug' => 'pizza-hut',
                'logo' => 'https://logo.clearbit.com/pizzahut.com',
                'website_url' => 'https://www.pizzahut.com',
                'description' => 'Pizza delivery, carryout, and dine-in.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'cj',
                'categories' => ['food-drinks'],
                'coupons' => [
                    ['title' => 'Large Pizza from £9.99', 'code' => null, 'type' => 'deal', 'discount_value' => 'From £9.99', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Starbucks',
                'slug' => 'starbucks',
                'logo' => 'https://logo.clearbit.com/starbucks.com',
                'website_url' => 'https://www.starbucks.com',
                'description' => 'Coffee, tea, and food. Order ahead with the app.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'direct',
                'categories' => ['food-drinks'],
                'coupons' => [
                    ['title' => 'Earn Stars with Every Purchase', 'code' => null, 'type' => 'deal', 'discount_value' => 'Rewards', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Nandos',
                'slug' => 'nandos',
                'logo' => 'https://logo.clearbit.com/nandos.com',
                'website_url' => 'https://www.nandos.com',
                'description' => 'PERi-PERi chicken restaurant. Flame-grilled goodness.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'awin',
                'categories' => ['food-drinks'],
                'coupons' => [
                    ['title' => 'Free Delivery on Orders Over £15', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free Ship', 'is_verified' => true],
                ],
            ],

            // ══════════════════════════════════════════════════════════════════
            // HOME & GARDEN (10 stores)
            // ══════════════════════════════════════════════════════════════════
            [
                'name' => 'IKEA',
                'slug' => 'ikea',
                'logo' => 'https://logo.clearbit.com/ikea.com',
                'website_url' => 'https://www.ikea.com',
                'description' => 'Affordable furniture, home accessories, and inspiration.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['home-garden'],
                'coupons' => [
                    ['title' => 'IKEA Family Member Discounts', 'code' => null, 'type' => 'deal', 'discount_value' => 'Member', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Wayfair',
                'slug' => 'wayfair',
                'logo' => 'https://logo.clearbit.com/wayfair.com',
                'website_url' => 'https://www.wayfair.com',
                'description' => 'Furniture, home decor, and more at great prices.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'cj',
                'categories' => ['home-garden'],
                'coupons' => [
                    ['title' => '10% Off First Order', 'code' => 'WAYFAIR10', 'type' => 'code', 'discount_value' => '10%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Home Depot',
                'slug' => 'home-depot',
                'logo' => 'https://logo.clearbit.com/homedepot.com',
                'website_url' => 'https://www.homedepot.com',
                'description' => 'Home improvement, tools, and building materials.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'cj',
                'categories' => ['home-garden'],
                'coupons' => [
                    ['title' => 'Free Delivery on $45+ Orders', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free Ship', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'B&Q',
                'slug' => 'b-and-q',
                'logo' => 'https://logo.clearbit.com/diy.com',
                'website_url' => 'https://www.diy.com',
                'description' => 'UK home improvement and garden retailer.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['home-garden'],
                'coupons' => [
                    ['title' => 'Up to 50% Off Garden Furniture', 'code' => null, 'type' => 'sale', 'discount_value' => '50%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Dunelm',
                'slug' => 'dunelm',
                'logo' => 'https://logo.clearbit.com/dunelm.com',
                'website_url' => 'https://www.dunelm.com',
                'description' => 'Home furnishings, bedding, curtains, and furniture.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['home-garden'],
                'coupons' => [
                    ['title' => 'Free Click & Collect', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'John Lewis',
                'slug' => 'john-lewis',
                'logo' => 'https://logo.clearbit.com/johnlewis.com',
                'website_url' => 'https://www.johnlewis.com',
                'description' => 'Quality furniture, fashion, electricals, and homeware.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['home-garden', 'electronics', 'apparel-clothing'],
                'coupons' => [
                    ['title' => 'Never Knowingly Undersold', 'code' => null, 'type' => 'deal', 'discount_value' => 'Price Match', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Argos',
                'slug' => 'argos',
                'logo' => 'https://logo.clearbit.com/argos.co.uk',
                'website_url' => 'https://www.argos.co.uk',
                'description' => 'Shop online for electronics, home, garden, toys, and more.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['home-garden', 'electronics'],
                'coupons' => [
                    ['title' => 'Same Day Delivery from £3.95', 'code' => null, 'type' => 'deal', 'discount_value' => 'Fast Ship', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Made.com',
                'slug' => 'made',
                'logo' => 'https://logo.clearbit.com/made.com',
                'website_url' => 'https://www.made.com',
                'description' => 'Designer furniture and homeware at affordable prices.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'awin',
                'categories' => ['home-garden'],
                'coupons' => [
                    ['title' => 'Up to 40% Off in Sale', 'code' => null, 'type' => 'sale', 'discount_value' => '40%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Habitat',
                'slug' => 'habitat',
                'logo' => 'https://logo.clearbit.com/habitat.co.uk',
                'website_url' => 'https://www.habitat.co.uk',
                'description' => 'Modern furniture and home accessories with character.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'awin',
                'categories' => ['home-garden'],
                'coupons' => [
                    ['title' => '20% Off Lighting', 'code' => 'LIGHT20', 'type' => 'code', 'discount_value' => '20%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'The Range',
                'slug' => 'the-range',
                'logo' => 'https://logo.clearbit.com/therange.co.uk',
                'website_url' => 'https://www.therange.co.uk',
                'description' => 'Home, garden, furniture, and DIY at great prices.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'awin',
                'categories' => ['home-garden'],
                'coupons' => [
                    ['title' => 'Free Click & Collect', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free', 'is_verified' => true],
                ],
            ],

            // ══════════════════════════════════════════════════════════════════
            // BABIES & KIDS (5 stores)
            // ══════════════════════════════════════════════════════════════════
            [
                'name' => "Carter's",
                'slug' => 'carters',
                'logo' => 'https://logo.clearbit.com/carters.com',
                'website_url' => 'https://www.carters.com',
                'description' => "America's favorite baby and kids clothing brand.",
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'cj',
                'categories' => ['babies-kids', 'apparel-clothing'],
                'coupons' => [
                    ['title' => '50% Off Everything', 'code' => 'CARTERS50', 'type' => 'code', 'discount_value' => '50%', 'is_verified' => true],
                ],
            ],
            [
                'name' => "The Children's Place",
                'slug' => 'the-childrens-place',
                'logo' => 'https://logo.clearbit.com/childrensplace.com',
                'website_url' => 'https://www.childrensplace.com',
                'description' => 'Affordable kids clothing for newborns to size 14.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'cj',
                'categories' => ['babies-kids', 'apparel-clothing'],
                'coupons' => [
                    ['title' => '60% Off Sitewide', 'code' => 'TCP60', 'type' => 'code', 'discount_value' => '60%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Mothercare',
                'slug' => 'mothercare',
                'logo' => 'https://logo.clearbit.com/mothercare.com',
                'website_url' => 'https://www.mothercare.com',
                'description' => 'Baby products, maternity wear, and nursery essentials.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['babies-kids'],
                'coupons' => [
                    ['title' => '15% Off First Order', 'code' => 'MOTHER15', 'type' => 'code', 'discount_value' => '15%', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Smyths Toys',
                'slug' => 'smyths-toys',
                'logo' => 'https://logo.clearbit.com/smythstoys.com',
                'website_url' => 'https://www.smythstoys.com',
                'description' => 'Toys, outdoor play, video games, and more for kids.',
                'cashback_rate' => 0.00,
                'is_featured' => true,
                'network' => 'awin',
                'categories' => ['babies-kids'],
                'coupons' => [
                    ['title' => 'Free Click & Collect', 'code' => null, 'type' => 'deal', 'discount_value' => 'Free', 'is_verified' => true],
                ],
            ],
            [
                'name' => 'Kidly',
                'slug' => 'kidly',
                'logo' => 'https://logo.clearbit.com/kidly.co.uk',
                'website_url' => 'https://www.kidly.co.uk',
                'description' => 'Curated baby and kids products from the best brands.',
                'cashback_rate' => 0.00,
                'is_featured' => false,
                'network' => 'awin',
                'categories' => ['babies-kids'],
                'coupons' => [
                    ['title' => '10% Off First Order', 'code' => 'KIDLY10', 'type' => 'code', 'discount_value' => '10%', 'is_verified' => true],
                ],
            ],
        ];

        $this->command->info('Seeding 100 stores with logos...');

        foreach ($stores as $data) {
            $coupons = $data['coupons'] ?? [];
            $categorySlugs = $data['categories'] ?? [];
            unset($data['coupons'], $data['categories']);

            // Create or update store
            $store = Store::updateOrCreate(
                ['slug' => $data['slug']],
                array_merge($data, ['is_active' => true])
            );

            // Attach categories
            if (!empty($categorySlugs)) {
                $categoryIds = Category::whereIn('slug', $categorySlugs)->pluck('id');
                $store->categories()->syncWithoutDetaching($categoryIds);
            }

            // Create coupons
            foreach ($coupons as $couponData) {
                $store->coupons()->updateOrCreate(
                    ['title' => $couponData['title']],
                    array_merge($couponData, [
                        'is_active' => true,
                        'click_count' => rand(100, 5000),
                        'is_verified' => $couponData['is_verified'] ?? false,
                        'is_exclusive' => $couponData['is_exclusive'] ?? false,
                        'destination_url' => $data['website_url'],
                        'expires_at' => $couponData['expires_at'] ?? now()->addDays(rand(7, 90)),
                    ])
                );
            }

            $this->command->info("✓ {$data['name']}");
        }

        $this->command->info('');
        $this->command->info('✅ Successfully seeded ' . count($stores) . ' stores with logos and coupons!');
    }
}
